export { default as Navbar } from './Navbar'
export { default as Notice } from './Notice'
export { default as Footer } from './Footer'
export { default as FeaturedCard } from './FeaturedCard'
export { default as Gender } from './Gender'
